package:
  name: xmle
  version: "0.1.16"

source:
  path: ../

requirements:
  build:
    - python>=3.6
  host:
    - python>=3.6
    - pandas
    - cloudpickle
    - jpn::filez>=1.0.2
  run:
    - python>=3.6
    - pandas
    - cloudpickle
    - jpn::filez>=1.0.2
  
test:
  # Python imports
  imports:
    - xmle

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  license: MIT
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
